### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by msgoussi** [r-lib/zip#54] opened 2020-07-08 12:31 UTC
Let say i have a file is called ""ô1.png" ("\u00f41.png"), when i try to zip it, i get an error.
zip::zipr("x.zip", files = "ô1.png")
Error in zip_internal(zipfile, files, recurse, compression_level, append = FALSE,  : 
  zip error: `Cannot add file `Ã´1.png` to archive `x.zip`` in file `zip.c:394`

**Comment by gaborcsardi** [comment] 2020-07-08 12:35
Duplicate of #53 I believe.

**Closed** 2020-07-10 14:56 UTC
