### ISSUE TITLE
zip folder appears empty after zipping

### ISSUE THREAD

**Issue by cimentadaj** [r-lib/zip#10] opened 2018-07-30 17:27 UTC
When trying to zip [this](https://ufile.io/qkqv7) Stata file I can successfully zip it as you can see in the reprex below

```r
dir_path <- "C:\\Users\\cimentadaj\\Desktop\\Documents\\all_repos\\spain_shiny\\shiny\\test"
file_path <- paste0(dir_path, "\\ESS1e06_5.dta")
zip::zip(paste0(dir_path, "\\ess.zip"), file_path)
zip::zip_list(paste0(dir_path, "\\ess.zip"))
#>                                                                                        filename
#> 1 C:\\Users\\cimentadaj\\Desktop\\Documents\\all_repos\\spain_shiny\\shiny\\test\\ESS1e06_5.dta
#>   compressed_size uncompressed_size
#> 1        11279990         190919822
```

However, when I search inside the `.zip` file in Windows it appears as if it's empty:
![ess_zip](https://user-images.githubusercontent.com/8180025/43412703-50315388-942e-11e8-80b5-74a617ac8244.png)

If I unzip it with 7zip then I can see the files. However, zipping with `utils::zip` allows me both to see the files in the above picture and see them when unzipping with 7zip.

Maybe this is a Windows problem so here's my session info on a Windows 10.

```r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       Europe/Paris                
#>  date     2018-07-30
#> Packages -----------------------------------------------------------------
#>  package   * version date       source                         
#>  backports   1.1.2   2017-12-13 CRAN (R 3.4.3)                 
#>  base      * 3.4.4   2018-03-15 local                          
#>  compiler    3.4.4   2018-03-15 local                          
#>  datasets  * 3.4.4   2018-03-15 local                          
#>  devtools    1.13.5  2018-02-18 CRAN (R 3.4.3)                 
#>  digest      0.6.15  2018-01-28 CRAN (R 3.4.3)                 
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.4.4)                 
#>  formatR     1.5     2017-04-25 CRAN (R 3.4.4)                 
#>  graphics  * 3.4.4   2018-03-15 local                          
#>  grDevices * 3.4.4   2018-03-15 local                          
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.4)                 
#>  knitr       1.20    2018-02-20 CRAN (R 3.4.4)                 
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.4)                 
#>  memoise     1.1.0   2018-03-20 Github (hadley/memoise@06d16ec)
#>  methods   * 3.4.4   2018-03-15 local                          
#>  Rcpp        0.12.17 2018-05-18 CRAN (R 3.4.4)                 
#>  rmarkdown   1.9     2018-03-01 CRAN (R 3.4.4)                 
#>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.4)                 
#>  stats     * 3.4.4   2018-03-15 local                          
#>  stringi     1.1.7   2018-03-12 CRAN (R 3.4.4)                 
#>  stringr     1.3.1   2018-05-10 CRAN (R 3.4.4)                 
#>  tools       3.4.4   2018-03-15 local                          
#>  utils     * 3.4.4   2018-03-15 local                          
#>  withr       2.1.2   2018-06-26 Github (r-lib/withr@fe56f20)   
#>  yaml        2.1.18  2018-03-08 CRAN (R 3.4.4)                 
#>  zip         1.0.0   2017-04-25 CRAN (R 3.4.4)
```

**Comment by gaborcsardi** [comment] 2018-07-30 19:44
Which version of zip was this?  Could you pls try the GitHub version as well? I think this might have been fixed there.

**Comment by cimentadaj** [comment] 2018-07-30 19:56
I was using version `1.0.0` but the same behaviour is present with the GH version.

**Comment by AndrewBigMac** [comment] 2018-08-14 15:00
I'm seeing the same behaviour.

**Comment by AndrewBigMac** [comment] 2018-08-15 08:16
The problem seems to have been resolved by NOT using complete file paths for the file list and just the file names.

**Comment by gaborcsardi** [comment] 2019-02-17 23:54
Unfortunately the file is gone, so I cannot reproduce this. Please reopen if you still have this problem.

**Closed by gaborcsardi** 2019-02-17 23:54 UTC
