### ISSUE TITLE
Windows cannot complete the extraction. The Compressed (zipped) Folder '<file path>' is invalid

### ISSUE THREAD

**Issue by RadioPete24** [r-lib/zip#3] opened 2017-11-01 23:51 UTC
@gaborcsardi

I'm new to using this package, and so have a couple observations using this package when creating zip folders in R using a Windows platform.
- After creating the zip file in R, the contents of the zip file cannot be viewed from Windows explorer. 
- When attempting to extract with the option of 'Extract all..." , the message 'Windows cannot complete the extraction. The Compressed (zipped) Folder '<file path>' is invalid' shows up.
- Using the 'unzip' package also gives a response with similar outcome: 'In unzip(choose.files(), choose.dir()) :  requested file not found in the zip file'
- Using a winzip tool, however, the files are extracted along with all of the old junkpaths.

Is there anyway to avoid compressing the files with their junkpaths?

**Comment by gaborcsardi** [comment] 2017-11-02 11:03
Can you please try to give me a reproducible example? E.g. some directories and files to compress, and the code you are running? Thanks.

**Comment by RadioPete24** [comment] 2017-11-02 16:11
The code I'm running:
#files in the same folder
pathOut <- file.path("<path_to_folder>") #6 directories leading up to the folder
list_of_files <- c("file1.pdf", "file2.pdf", "file3.dat")
path_to_files <- file.path(pathOut, list_of_files)
#creating the zipfile
zip(zipfile = file.path("<zipfilename>.zip"
, files = path_to_files
)

Other details: I'm using it in Windows 7, R version 3.4.2

**Comment by gaborcsardi** [comment] 2017-11-02 16:17
what is in `pathOut`?

**Comment by RadioPete24** [comment] 2017-11-02 17:36
pathOut was my way of avoiding input of the whole pathway for each file in the list of files to archive.
e.g. ( pathOut <- file.path("J:", "folder1", "folder2", "folder3"))

**Comment by gaborcsardi** [comment] 2017-11-02 17:42
I am sorry, but this is not a reproducible example, I cannot reproduce your problem. Your code is not even syntactically correct.

**Comment by RadioPete24** [comment] 2017-11-02 18:50
Hi,

Coding is still the same and syntax hasn't changed. Perhaps you could inform me how it's not syntactically correct. I've only modified the folder and file names to keep things relevant.

pathOut <-  file.path("J:", "folder1", "folder2", "folder3")
list_of_files <- c("file1.pdf",
                         , "file2.dat"
                         , "file3.pdf"
                         , "file4.dat"
                         )
pathOut2 <- file.path (pathOut, list_of_files)
pathOut2
# gives the list
#[1] "J:/folder1/folder2/folder3/file1.pdf"
#[2] "J:/folder1/folder2/folder3/file2.dat"
#[3] "J:/folder1/folder2/folder3/file3.pdf"
#[4] "J:/folder1/folder2/folder3/file4.dat"
zip(zipfile = file.path("pathOut", "file_name.zip") 
    , files = pathOut2
    )

I've tried the unzip package, windows explorer's 'Extract All...", winzip, and have only managed to open the zipfile with 7-zip. When the contents are extracted into another folder, junkpaths (e.i. J:/folder1/folder2/folder3/...) are created.

**Comment by gaborcsardi** [comment] 2017-12-18 12:38
Sorry, this took a while. Can you please try the GitHub version now?

**Comment by RadioPete24** [comment] 2018-01-16 23:16
Instead of including all the parent folders in the zip file, the zip and zipr functions give an error message:

> Error in .Call(c_R_zip_zip, zipfile, data$key, data$file, data$dir, as.integer(compression_level),  : 
>   Incorrect number of arguments (6), expecting 4 for 'R_zip_zip'
> In addition: Warning message:
> In warn_for_dotdot(data$key) :
>   Some paths reference parent directory, creating non-portable zip file_

**Comment by gaborcsardi** [comment] 2019-02-17 23:55
Closing this, as no reproducible example is available.

**Closed by gaborcsardi** 2019-02-17 23:55 UTC
